package com.tuapp.servicios.domain.enums;
public enum TipoNotificacion {
    FACTURA_AGREGADA,
    FACTURA_VENCE_7_DIAS,
    FACTURA_VENCE_3_DIAS,
    FACTURA_VENCE_HOY,
    FACTURA_VENCIDA,
    PAGO_EXITOSO,
    PAGO_FALLIDO,
    PAGO_CONFIRMADO,
    FACTURA_POR_VENCER,
    ANOMALIA_DETECTADA,
    ANALISIS_LISTO,
    AUTOPAGO_EJECUTADO,
    AUTOPAGO_FALLIDO
}
